routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('loginmasyarakat', function () {
    return view('welcome'); 
})->name('login.masyarakat');

Route::get('login', 'LoginController@getLogin')->name('login');
Route::post('proseslogin','LoginController@postLogin');
Route::get('logout','LoginController@logout');
Route::get('logoutmasyarakat','LoginController@logoutmasyarakat');
Route::view('register', 'register');
Route::post('regis', 'MasyarakatController@regis')->name('register');

Route::group(['middleware'=>'auth:admin'], function(){
    Route::get('dashboard','DashboardController@index');

    // Petugas
    Route::resource('petugas', 'PetugasController');

    // Masyarakat
    Route::resource('masyarakat', 'MasyarakatController');

    // Pengaduan
    Route::get('pengaduan','PengaduanController@index');
    Route::get('pengaduan_p/{id}','PengaduanController@proses')->name('pengaduan.proses');
    Route::get('pengaduan_s/{id}','PengaduanController@selesai')->name('pengaduan.selesai');
    Route::get('pengaduan_t/{id}','PengaduanController@tanggapan')->name('pengaduan.tanggapan');
    
    // Tanggapan
    Route::post('tambahtanggapan','TanggapanController@tambah');
    Route::get('tanggapan','TanggapanController@index');
    Route::get('tanggapan/{id}','TanggapanController@edit')->name('tanggapan.edit');
    Route::patch('tanggapans/{id}','TanggapanController@update')->name('tanggapan.update');
    Route::delete('tanggapand/{id}','TanggapanController@destroy')->name('tanggapan.destroy');

    //Laporan
    Route::view('laporan','admin/laporan.index');
    Route::get('rekap_laporan','LaporanController@rekap');

    //Transaksi
    Route::post('/store_tagihan', 'TagihanController@store');
    Route::get('/list', 'TagihanController@index');
    Route::get('/payment/{id}', 'TagihanController@payment')->name('payment');
    Route::post('/bayar/{id}', 'TagihanController@bayar')->name('bayar');
    Route::get('/invoice/{id}', 'TagihanController@invoice')->name('invoice');
    Route::view('/tambah', 'admin.ListTagihan.tambah');
});


Route::get('/','MasyarakatController@depan');

Route::group(['middleware'=>'auth:masyarakat'], function(){
    Route::get('masyarakat_pengaduan','MasyarakatController@pengaduan');
    Route::post('prosespengaduan','MasyarakatController@prosespengaduan');
    Route::get('history','MasyarakatController@history');
    Route::get('lihattanggapan/{id}','MasyarakatController@tanggapan')->name('tanggapans');
});

app/Models/masyarakat.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class masyarakat extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */

    protected $table = "tbl_mahasiswa";

    protected $primaryKey = "nik";

    protected $fillable = [
        'nik','nama', 'username', 'password'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 
    ];
    public function admin(){
        return $this->belongsTo(admin::class);
    }
}

app/Http/Controllers/MasyarakatController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use Intervention\Image\Facades\Image;

class MasyarakatController extends Controller
{

    private function _validation(Request $request)
    {
        $validation = $request->validate([
            'nik' => 'required|max:16',
            'nama' => 'required|max:35',
            'username' => 'required|max:25',
            'password' => 'required',
        ],
        [
            'nik.required' => 'Harus diisi',
            'nik.max' => 'Huruf jangan melebihi 16',
            'nama.required' => 'Harus diisi',
            'nama.max' => 'Huruf jangan melebihi 35',
            'username.required' => 'Harus diisi',
            'username.max' => 'Huruf jangan melebihi 25',
            'password.required' => 'harus diisi',
        ]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $data = DB::table('tbl_mahasiswa')
        ->where('nik','like',"%{$request->keyword}%")
        ->orWhere('nama','like',"%{$request->keyword}%")
        ->orWhere('username','like',"%{$request->keyword}%")
        ->paginate(5);
        return view('admin/masyarakat.index',['data'=>$data]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin/masyarakat.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->_validation($request);
        $password = $request->password;
        DB::table('tbl_mahasiswa')->insert([
            'nik'=>$request->nik,
            'nama'=>$request->nama,
            'username'=>$request->username,
            'password'=>bcrypt($password),
            'telp'=>$request->telp
        ]);
        return redirect('masyarakat')->with('message','Berhasil ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = DB::table('tbl_mahasiswa')->where('nik',$id)->first();
        return view('admin/masyarakat.edit',['data'=>$data]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->_validation($request);
        $password = $request->password;
        DB::table('tbl_mahasiswa')->where('nik',$id)->update([
            'nik'=>$request->nik,
            'nama'=>$request->nama,
            'username'=>$request->username,
            'password'=>bcrypt($password),
            'telp'=>$request->telp
        ]);
        return redirect('masyarakat')->with('message','Berhasil diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::table('tbl_mahasiswa')->where('nik',$id)->delete();
        return redirect()->back()->with('message','Berhasil dihapus');
    }

    public function depan()
    {
        return view('masyarakat.index');
    }

    public function regis(Request $request)
    {
        $this->_validation($request);
        $password = $request->password;
        DB::table('tbl_mahasiswa')->insert([
            'nik'=>$request->nik,
            'nama'=>$request->nama,
            'username'=>$request->username,
            'password'=>bcrypt($password),
            'telp'=>$request->telp
        ]);
        return redirect('loginmasyarakat')->with('message','Register berhasil ditambahkan');
    }

    public function pengaduan()
    {
        return view('masyarakat.pengaduan');
    }

    public function prosespengaduan(Request $request)
    {
        $lokasi_file = public_path('/assets/img/produk');
        
        if(!empty($request->gambar_masakan))
        {
        //Resize Gambar Masakan
        $gambar_masakan = $request->file('gambar_masakan');
        $nama_gambar_masakan = 'produk_'. time() . '.' . $gambar_masakan->getClientOriginalExtension();
        $resize_gambar_masakan = Image::make($gambar_masakan->getRealPath());
        $resize_gambar_masakan->save($lokasi_file . '/' . $nama_gambar_masakan);
        //End resize Gambar Masakan
        
        $tanggal = date('Y-m-d');
        DB::table('tbl_pengaduan')->insert([
            'tanggal_pengaduan'=>$tanggal,
            'nik_id'=>Auth::guard('masyarakat')->user()->nik,
            'isi_laporan'=>$request->isi,
            'status'=>'terkirim',
            'foto'=>$nama_gambar_masakan
        ]);
        }else{
            $tanggal = date('Y-m-d');
            DB::table('tbl_pengaduan')->insert([
                'tanggal_pengaduan'=>$tanggal,
                'nik_id'=>Auth::guard('masyarakat')->user()->nik,
                'isi_laporan'=>$request->isi,
                'status'=>'terkirim'
            ]);
        }

        return redirect('/history')->with('message','Pengaduan terkirim');
        
    }

    public function history()
    {
        $data = DB::table('tbl_pengaduan')->where('nik_id',Auth::guard('masyarakat')->user()->nik)->get();
        return view('masyarakat.history',['data'=>$data]);
    }

    public function tanggapan($id)
    {
        $data = DB::table('tbl_tanggapan')->where('pengaduan_id',$id)->first();
        return view('masyarakat.tanggapan',['data'=>$data]);
    }
}

resources/views/admin/masyarakat/create.blade.php
@extends('admin/layout.master')

@section('title','masyarakat')
@section('title2','tambah')
@section('masyarakat','active')
@section('konten')

<div class="card">
  <div class="card-header">
    <h4>Tambah masyarakat</h4>
  </div>
  <div class="card-body">
    <form action="{{ route('masyarakat.store') }}" method="POST">
    @csrf
    <div class="row">

        {{-- nik --}}
        <div class="col-md-6">
            <div class="form-group">
            <label @error('nik') class="text-danger" @enderror>
                nik
                @error('nik')
                | {{ $message }}
                @enderror
            </label>
            <input type="text" name="nik" value="{{old('nik')}}" class="form-control" autocomplete="off">  
            </div>
        </div>

        {{-- nama --}}
        <div class="col-md-6">
            <div class="form-group">
              <label @error('nama') class="text-danger" @enderror>
                nama 
                @error('nama')
                  | {{ $message }}
                @enderror
              </label>
              <input type="text" name="nama" value="{{old('nama')}}" class="form-control" autocomplete="off">  
            </div>
          </div>

          {{-- username --}}
          <div class="col-md-6">
            <div class="form-group">
              <label @error('username') class="text-danger" @enderror>
                Username
                @error('username')
                  | {{ $message }}
                @enderror
              </label>
              <input type="text" name="username" value="{{old('username')}}" class="form-control" autocomplete="off">  
            </div>
          </div>
          
          {{-- password --}}
          <div class="col-md-6">
            <div class="form-group">
              <label @error('password') class="text-danger" @enderror>
                password
                @error('password')
                  | {{ $message }}
                @enderror
              </label>
              <input type="password" name="password" value="{{old('password')}}" class="form-control" autocomplete="off">  
            </div>
          </div>

            {{-- kompetensi --}}
          <div class="col-md-6">
            <div class="form-group">
              <label @error('telp') class="text-danger" @enderror>
                telp
                @error('telp')
                  | {{ $message }}
                @enderror
              </label>
              <input type="text" name="telp" value="{{old('telp')}}" class="form-control" autocomplete="off">  
            </div>
          </div>

          

    </div>    
      <div class="card-footer text-right">
        <button class="btn btn-primary mr-1" type="submit">Submit</button>
        <a href="/petugas" class="btn btn-secondary" type="reset">Cancel</a>
      </div>
    </form>
  </div>
</div>

@endsection
@push('page-scripts')
<script src = "https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script type="text/javascript">
  $('#select2').select2();
</script>
@endpush

resources/views/admin/masyarakat/edit.blade.php
@extends('admin/layout.master')

@section('title','masyarakat')
@section('title2','tambah')
@section('masyarakat','active')
@section('konten')

<div class="card">
  <div class="card-header">
    <h4>Edit masyarakat</h4>
  </div>
  <div class="card-body">
    <form action="{{ route('masyarakat.update',$data->nik) }}" method="POST">
        @method('PATCH')
    @csrf
    <div class="row">

        {{-- nik --}}
        <div class="col-md-6">
            <div class="form-group">
              <label @error('nik') class="text-danger" @enderror>
                nik
                @error('nik')
                  | {{ $message }}
                @enderror
              </label>
              <input type="text" name="nik"  
              @if (old('nik'))
                  value="{{old('nik')}}"
              @else
                  value="{{ $data->nik }}"
              @endif
              class="form-control" autocomplete="off"> 
            </div>
          </div>

        {{-- nama --}}
        <div class="col-md-6">
            <div class="form-group">
              <label @error('nama') class="text-danger" @enderror>
                nama masyarakat
                @error('nama')
                  | {{ $message }}
                @enderror
              </label>
              <input type="text" name="nama"  
              @if (old('nama'))
                  value="{{old('nama')}}"
              @else
                  value="{{ $data->nama }}"
              @endif
              class="form-control" autocomplete="off">  
            </div>
          </div>

          {{-- username --}}
          <div class="col-md-6">
            <div class="form-group">
              <label @error('username') class="text-danger" @enderror>
                Username
                @error('username')
                  | {{ $message }}
                @enderror
              </label>
              <input type="text" name="username"  
              @if (old('username'))
                  value="{{old('username')}}"
              @else
                  value="{{ $data->username }}"
              @endif
              class="form-control" autocomplete="off">  
            </div>
          </div>
          
          {{-- password --}}
          <div class="col-md-6">
            <div class="form-group">
              <label @error('password') class="text-danger" @enderror>
                password
                @error('password')
                  | {{ $message }}
                @enderror
              </label>
              <input type="password" name="password"  
              @if (old('password'))
                  value="{{old('password')}}"
              @else
                  
              @endif
              class="form-control" autocomplete="off">  
            </div>
          </div>

          {{-- telp --}}
          <div class="col-md-6">
            <div class="form-group">
              <label @error('telp') class="text-danger" @enderror>
                telp
                @error('telp')
                  | {{ $message }}
                @enderror
              </label>
              <input type="text" name="telp"  
              @if (old('telp'))
                  value="{{old('telp')}}"
              @else
                  value="{{ $data->telp }}"
              @endif
              class="form-control" autocomplete="off">  
            </div>
          </div>

          

    </div>    
      <div class="card-footer text-right">
        <button class="btn btn-primary mr-1" type="submit">Submit</button>
        <a href="/masyarakat" class="btn btn-secondary" type="reset">Cancel</a>
      </div>
    </form>
  </div>
</div>

@endsection
@push('page-scripts')
<script src = "https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script type="text/javascript">
  $('#select2').select2();
</script>
@endpush

resources/views/admin/masyarakat/index.blade.php
@extends('admin/layout.master')

@section('title','Masyarakat')
@section('title2','index')
@section('masyarakat','active')

@section('konten')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">

                    {{-- Button tambah --}}
                    <a href="{{ route('masyarakat.create') }}" class="btn btn-warning mb-4"><i class="fas fa-plus text-light"></i></a>
                    
                    {{-- Form search --}}
                    <div class="float-right">
                        <form action="?" method="GET">
                          <div class="input-group mb-3">
                            <input name="keyword" id="caribuku" type="text" class="form-control" placeholder="Cari..." aria-label="Cari" aria-describedby="button-addon2" value="{{ Request()->keyword }}" autocomplete="off">
                            <div class="input-group-append">
                              <button id="btncaribuku" class="btn btn-outline-warning bg-warning" type="submit" id="button-addon2"><i class="fas fa-search text-light"></i></button>
                            </div>
                          </div>
                        </form>
                    </div>

                    {{-- Alert --}}
                    @if(session('message'))
                    <div class="alert alert-success alert-dismissible show fade">
                        <div class="alert-body">
                        <button class="close" data-dismiss="alert">
                            <span>×</span>
                        </button>
                        {{ session('message') }}
                        </div>
                    </div>
                    @endif

                    {{-- tabel --}}
                    <table class="table">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Nik</th>
                                <th>nama</th>
                                <th>Telp</th>
                                <th>username</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @php
                                $no = 1
                            @endphp
                            @foreach ($data as $item)
                                <tr>
                                    <td>{{ $no++ }}</td>
                                    <td>{{ $item->nik }}</td>
                                    <td>{{ $item->nama }}</td>
                                    <td>{{ $item->telp }}</td>
                                    <td>{{ $item->username }}</td>
                                    <td>
                                        <a href="{{ route('masyarakat.edit',$item->nik) }}" class="btn btn-warning"><i class="fas fa-edit mb-2"></i></a>
                                        <a href="#" data-id="" class="btn btn-danger confirm_script-{{$item->nik}} mr-3">
                                            <form action="{{ route('masyarakat.destroy',$item->nik)}}" class="delete_form-{{$item->nik}}" method="POST">
                                            @method('DELETE')
                                            @csrf
                                            </form>
                                            <i class="fas fa-trash"></i>
                                          </a>
                                    </td>
                                </tr>
                                @push('page-scripts')
                                <script src="{{ asset('node_modules/sweetalert/dist/sweetalert.min.js')}}"></script>

                                @endpush

                                @push('after-scripts')

                                <script>
                                $(".confirm_script-{{$item->nik}}").click(function(e) {
                                // id = e.target.dataset.id;
                                swal({
                                    title: 'Yakin hapus data?',
                                    text: 'Data yang dihapus tidak bisa di kembalikan',
                                    icon: 'warning',
                                    buttons: true,
                                    dangerMode: true,
                                    })
                                    .then((willDelete) => {
                                    if (willDelete) {
                                        $('.delete_form-{{$item->nik}}').submit();
                                    } else {
                                    swal('Hapus data telah di batalkan');
                                    }
                                    });
                                });
                                </script>
                                @endpush
                            @endforeach
                        </tbody>
                    </table>
                    {{ $data->links() }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection